import { type EventDataMainpage } from './types'

export const MOCK_EVENTS: EventDataMainpage[] = [
    {
        id: 1,
        title: 'Airshow 2026',
        organizer: 'Aeromodelling Club, IIT Bombay',
        image: '',
        date: '12 Jan',
        time: '7:30 PM',
        location: 'LA 202',
        rating: 4.8,
        reviewCount: 120,
        description: 'Random text...',
    },
    {
        id: 2,
        title: 'Airshow 2026',
        organizer: 'Aeromodelling Club, IIT Bombay',
        image: '',
        date: '12 Jan',
        time: '7:30 PM',
        location: 'LA 202',
        rating: 4.8,
        reviewCount: 120,
        description: 'Random text...',
    },
    {
        id: 3,
        title: 'Airshow 2026',
        organizer: 'Aeromodelling Club, IIT Bombay',
        image: '',
        date: '12 Jan',
        time: '7:30 PM',
        location: 'LA 202',
        rating: 4.8,
        reviewCount: 120,
        description: 'Random text...',
    },
    {
        id: 4,
        title: 'Airshow 2026',
        organizer: 'Aeromodelling Club, IIT Bombay',
        image: '',
        date: '12 Jan',
        time: '7:30 PM',
        location: 'LA 202',
        rating: 4.8,
        reviewCount: 120,
        description: 'Random text...',
    },
    {
        id: 5,
        title: 'Airshow 2026',
        organizer: 'Aeromodelling Club, IIT Bombay',
        image: '',
        date: '12 Jan',
        time: '7:30 PM',
        location: 'LA 202',
        rating: 4.8,
        reviewCount: 120,
        description: 'Random text...',
    },
    {
        id: 6,
        title: 'Airshow 2026',
        organizer: 'Aeromodelling Club, IIT Bombay',
        image: '',
        date: '12 Jan',
        time: '7:30 PM',
        location: 'LA 202',
        rating: 4.8,
        reviewCount: 120,
        description: 'Random text...',
    },
]
